# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='aadhaar_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mob_no',
            field=models.CharField(max_length=10),
        ),
    ]
