# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0002_auto_20170909_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='aadhaar_no',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='mob_no',
            field=models.IntegerField(default=12),
        ),
    ]
